### ISSUE TITLE
DP tests exit when not able to ping instances from associated dhcp namespace

### ISSUE THREAD

**Issue by mudit70** [noironetworks/noirotest#4]
Follow instructions on the following wiki page:
https://sites.google.com/a/noironetworks.com/noiro-wiki/engineering/run-automated-testsuites-on-your-fab

The output from the screen io is in the following file on the Fab7 Controller ( 10.30.120.107) : /tmp/dptestfailurelog.txt

**Comment by puppet-py** [comment]
As per the linux group-table, all mcast-groups in Comp-nodes got learned at the eth0(mgmt-intf) instead of the desired vtep opflex1.4093. Hence all bcast traffic fails, thereby no ARP.

This niether a Automation/Harness issue nor a product bug but a setup issue.

**Comment by puppet-py** [comment]
Closing this issue going by the previous comment
